apiVersion: v1
kind: Service
metadata:
  name: cloudops-pulse-svc
spec:
  type: NodePort
  selector:
    app: cloudops-pulse
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30080
